"""init: maitres et classes

Revision ID: 2ff1f2f4564b
Revises: 
Create Date: 2026-07-07 22:57:47.106591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff1f2f4564b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maitres',
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('classes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=True),
    sa.Column('maitre_matricule', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maitre_matricule'], ['maitres.matricule'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    op.drop_table('maitres')
    # ### end Alembic commands ###
