"""init

Revision ID: d83b031bc476
Revises: 
Create Date: 2026-07-16 20:57:59.113039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b031bc476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maitres',
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('classes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=True),
    sa.Column('maitre_matricule', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maitre_matricule'], ['maitres.matricule'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('talibes',
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('nom_tuteur', sa.String(length=200), nullable=True),
    sa.Column('telephone_tuteur', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('classe_code', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classe_code'], ['classes.code'], ),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sourate', sa.String(length=100), nullable=False),
    sa.Column('nombre_versets', sa.Integer(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('talibe_matricule', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talibe_matricule'], ['talibes.matricule'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressions')
    op.drop_table('talibes')
    op.drop_table('classes')
    op.drop_table('maitres')
    # ### end Alembic commands ###
